language: node_js

node_js:
- '0.12'

branches:
  only:
  - blog

before_install:
- openssl aes-256-cbc -K $encrypted_b83a281ef741_key -iv $encrypted_b83a281ef741_iv
  -in doc/travis.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "叶帆"
- git config --global user.email yeziahehe@gmail.com
- git clone -b master git@github.com:Coryphaei/coryphaei.github.io.git .deploy_git

install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save

script:
- hexo clean
- hexo g
- hexo d
